// Библиотека контента (слой 3). АВТОГЕНЕРАЦИЯ из content.py — не правь
// вручную: меняй content.py и пересоздавай (parity с Python-версией).
// CSCA: подробный урок EN->RU + практика. DET: типы заданий Duolingo.

import { TRACK_6MIN, TRACK_EGE, TRACK_CSCA, TRACK_DET } from "./config.js";

export const CSCA_APP = "https://csca.app";
export const DET_APP = "https://englishtest.duolingo.com";
export const DET_PRACTICE = "https://englishtest.duolingo.com/prep";

export const SIX_MIN_EPISODES = [
  ["Why we hate open offices", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2019/ep-190411"],
  ["Is the customer always right?", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2020/ep-200206"],
  ["Does your age affect your opinions?", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2021/ep-210401"],
  ["The benefits of boredom", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2019/ep-190606"],
  ["How to make decisions", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2020/ep-201029"],
  ["The power of introverts", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2019/ep-190822"],
  ["Why do we cry?", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2021/ep-210617"],
  ["The problem with plastic", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2018/ep-181129"],
  ["Learning a language later in life", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2020/ep-200827"],
  ["The secrets of a good sleep", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2019/ep-191219"],
  ["Can we trust our memories?", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2021/ep-210909"],
  ["How to be a better listener", "https://www.bbc.co.uk/learningenglish/features/6-minute-english_2020/ep-200723"],
];

export const CSCA_LESSONS = [
  ["Functions: домен, область значений, чётность", "A function f maps every input x to exactly one output f(x). The DOMAIN is the set of x you are allowed to plug in; the RANGE is the set of outputs you get back. Two rules cover almost every CSCA question:\n  - a denominator can never be 0  ->  exclude those x;\n  - the argument of a square root or of log must be > 0  (for even roots, >= 0; for log, strictly > 0).\nExample: for f(x) = ln(x - 3) / sqrt(5 - x) you need x - 3 > 0 AND 5 - x > 0, so the domain is 3 < x < 5.\nPARITY: f is EVEN if f(-x) = f(x) (graph symmetric about the y-axis, e.g. x^2, cos x); f is ODD if f(-x) = -f(x) (symmetric about the origin, e.g. x^3, sin x). Most functions are neither.", "Функция f сопоставляет каждому входу x ровно один выход f(x). ОБЛАСТЬ ОПРЕДЕЛЕНИЯ (domain) — какие x вообще можно подставить; ОБЛАСТЬ ЗНАЧЕНИЙ (range) — какие выходы получаются. Два правила закрывают почти все вопросы CSCA:\n  - знаменатель не равен 0  ->  такие x выкидываем;\n  - под чётным корнем выражение >= 0, под логарифмом — строго > 0.\nПример: для f(x) = ln(x - 3) / sqrt(5 - x) нужно x - 3 > 0 И 5 - x > 0, значит домен: 3 < x < 5.\nЧЁТНОСТЬ: f чётная, если f(-x) = f(x) (график симметричен относительно оси y: x^2, cos x); нечётная, если f(-x) = -f(x) (симметрия относительно начала координат: x^3, sin x). Чаще всего — ни то, ни другое.", "Фильтр Functions на csca.app: 12-15 задач на домен и чётность. Ошибки — в mistake log.", 45],
  ["Тригонометрия: единичная окружность и тождества", "On the UNIT CIRCLE a point at angle θ has coordinates (cos θ, sin θ), and tan θ = sin θ / cos θ. Memorise the first quadrant exactly:\n  θ = 0, 30, 45, 60, 90 deg  ->  sin = 0, 1/2, sqrt2/2, sqrt3/2, 1.\nSigns by quadrant (ASTC / 'All Students Take Calculus'): Q1 all +, Q2 only sin +, Q3 only tan +, Q4 only cos +.\nCore identities you will reuse everywhere:\n  sin^2 θ + cos^2 θ = 1;\n  sin(2θ) = 2 sin θ cos θ;\n  cos(2θ) = cos^2 θ - sin^2 θ = 1 - 2 sin^2 θ;\n  sin(A ± B) = sin A cos B ± cos A sin B.\nTrick: if you know one ratio and the quadrant, use sin^2 + cos^2 = 1 to get the other, then pick the sign from the quadrant.", "На ЕДИНИЧНОЙ ОКРУЖНОСТИ точка под углом θ имеет координаты (cos θ, sin θ), а tan θ = sin θ / cos θ. Первую четверть знай наизусть:\n  θ = 0, 30, 45, 60, 90 град  ->  sin = 0, 1/2, sqrt2/2, sqrt3/2, 1.\nЗнаки по четвертям: I — всё +, II — только sin +, III — только tan +, IV — только cos +.\nТождества, которые нужны постоянно:\n  sin^2 θ + cos^2 θ = 1;\n  sin(2θ) = 2 sin θ cos θ;\n  cos(2θ) = cos^2 θ - sin^2 θ = 1 - 2 sin^2 θ;\n  sin(A ± B) = sin A cos B ± cos A sin B.\nПриём: знаешь одно отношение и четверть — через sin^2 + cos^2 = 1 находишь второе, а знак берёшь из четверти.", "csca.app, тема Trigonometry: 15 задач на значения и простые тождества. Формулы держи перед глазами, но старайся без подсказок.", 45],
  ["Последовательности и суммы (прогрессии)", "ARITHMETIC progression: each term adds a fixed d.\n  a_n = a_1 + (n - 1) d;   sum S_n = n (a_1 + a_n) / 2 = n/2 (2 a_1 + (n-1) d).\nGEOMETRIC progression: each term multiplies by a fixed ratio q.\n  a_n = a_1 * q^(n-1);   sum S_n = a_1 (q^n - 1) / (q - 1)  for q != 1.\nIf |q| < 1 the INFINITE sum converges: S = a_1 / (1 - q).\nTypical CSCA question: you are given two terms, say a_3 and a_7. Write both with the formula, divide (geometric) or subtract (arithmetic) to kill a_1, solve for q or d, then answer. Always check whether the sequence is arithmetic (constant difference) or geometric (constant ratio) before choosing the formula.", "АРИФМЕТИЧЕСКАЯ прогрессия: к каждому члену прибавляется постоянное d.\n  a_n = a_1 + (n - 1) d;   сумма S_n = n (a_1 + a_n) / 2 = n/2 (2 a_1 + (n-1) d).\nГЕОМЕТРИЧЕСКАЯ прогрессия: каждый член умножается на постоянное q.\n  a_n = a_1 * q^(n-1);   сумма S_n = a_1 (q^n - 1) / (q - 1)  при q != 1.\nЕсли |q| < 1, БЕСКОНЕЧНАЯ сумма сходится: S = a_1 / (1 - q).\nТипичный вопрос CSCA: даны два члена, например a_3 и a_7. Записываешь оба по формуле, делишь (геом.) или вычитаешь (арифм.), чтобы убрать a_1, находишь q или d — и отвечаешь. Сначала определи тип: постоянная разность (арифм.) или постоянное отношение (геом.).", "csca.app, тема Sequences: 15 задач на общий член и сумму. Отдельно потренируй задачи «даны два члена — найди прогрессию».", 45],
  ["Логарифмы и показательные", "A log answers 'to what power?': log_b(x) = y means b^y = x (with b > 0, b != 1, x > 0). The three laws do all the work:\n  log(xy) = log x + log y;\n  log(x/y) = log x - log y;\n  log(x^k) = k log x.\nChange of base: log_b(x) = ln x / ln b. Useful values: log_b(1) = 0, log_b(b) = 1.\nExponentials are the inverse: b^(m+n) = b^m * b^n, (b^m)^n = b^(mn), b^(-n) = 1 / b^n. To solve an exponential equation, take log of both sides; to solve a log equation, rewrite in exponential form and DON'T forget to check the domain (the argument must stay > 0).", "Логарифм отвечает на вопрос «в какую степень?»: log_b(x) = y значит b^y = x (при b > 0, b != 1, x > 0). Вся работа — в трёх законах:\n  log(xy) = log x + log y;\n  log(x/y) = log x - log y;\n  log(x^k) = k log x.\nСмена основания: log_b(x) = ln x / ln b. Полезно: log_b(1) = 0, log_b(b) = 1.\nПоказательные — обратные к логарифмам: b^(m+n) = b^m * b^n, (b^m)^n = b^(mn), b^(-n) = 1 / b^n. Показательное уравнение решают, логарифмируя обе части; логарифмическое — переписывая в показательный вид, и обязательно проверяют домен (аргумент должен остаться > 0).", "csca.app: 12-15 задач на свойства логарифмов и показательные уравнения. Особое внимание — проверке ОДЗ.", 40],
  ["Квадратичная функция и неравенства", "The parabola y = a x^2 + b x + c opens up if a > 0, down if a < 0. Its vertex is at x = -b / (2a). The DISCRIMINANT D = b^2 - 4 a c tells you the roots: D > 0 two real roots, D = 0 one (repeated), D < 0 none.\nRoots: x = (-b ± sqrt(D)) / (2a). Vieta: x_1 + x_2 = -b/a, x_1 * x_2 = c/a.\nQUADRATIC INEQUALITIES: find the roots, then read the sign of the parabola. For a > 0, a x^2 + b x + c > 0 holds OUTSIDE the roots (x < x_1 or x > x_2); it is < 0 BETWEEN the roots (x_1 < x < x_2). Sketching the parabola is faster and safer than memorising cases.", "Парабола y = a x^2 + b x + c ветвями вверх при a > 0 и вниз при a < 0. Вершина в x = -b / (2a). ДИСКРИМИНАНТ D = b^2 - 4 a c определяет корни: D > 0 — два корня, D = 0 — один (кратный), D < 0 — корней нет.\nКорни: x = (-b ± sqrt(D)) / (2a). Теорема Виета: x_1 + x_2 = -b/a, x_1 * x_2 = c/a.\nКВАДРАТНЫЕ НЕРАВЕНСТВА: находишь корни и смотришь знак параболы. При a > 0 выражение a x^2 + b x + c > 0 ВНЕ корней (x < x_1 или x > x_2), и < 0 МЕЖДУ корнями (x_1 < x < x_2). Быстрее и надёжнее нарисовать параболу, чем зубрить случаи.", "csca.app: 12 задач на корни, вершину и квадратные неравенства. Рисуй эскиз параболы для каждого неравенства.", 40],
  ["Аналитическая геометрия: прямая и расстояние", "Slope between two points: k = (y_2 - y_1) / (x_2 - x_1). Line through (x_0, y_0) with slope k: y - y_0 = k (x - x_0). General form: A x + B y + C = 0.\nParallel lines have EQUAL slopes; perpendicular lines have slopes whose product is -1 (k_1 * k_2 = -1).\nDistance between two points: d = sqrt((x_2 - x_1)^2 + (y_2 - y_1)^2).\nMidpoint: ((x_1 + x_2)/2, (y_1 + y_2)/2).\nDistance from a point (x_0, y_0) to line A x + B y + C = 0:\n  d = |A x_0 + B y_0 + C| / sqrt(A^2 + B^2).\nA very common CSCA task combines these: find the line, then the distance from a given point, or show two lines are perpendicular.", "Угловой коэффициент через две точки: k = (y_2 - y_1) / (x_2 - x_1). Прямая через (x_0, y_0) с наклоном k: y - y_0 = k (x - x_0). Общий вид: A x + B y + C = 0.\nУ параллельных прямых наклоны РАВНЫ; у перпендикулярных — произведение наклонов равно -1 (k_1 * k_2 = -1).\nРасстояние между точками: d = sqrt((x_2 - x_1)^2 + (y_2 - y_1)^2).\nСередина отрезка: ((x_1 + x_2)/2, (y_1 + y_2)/2).\nРасстояние от точки (x_0, y_0) до прямой A x + B y + C = 0:\n  d = |A x_0 + B y_0 + C| / sqrt(A^2 + B^2).\nЧастый вопрос CSCA собирает всё вместе: найти прямую, затем расстояние от точки, или доказать перпендикулярность.", "csca.app, фильтр Geometry: 15 задач на прямую, расстояние и перпендикулярность.", 45],
  ["Конические сечения: окружность, эллипс, гипербола, парабола", "CIRCLE: (x - a)^2 + (y - b)^2 = r^2, centre (a, b), radius r.\nELLIPSE: x^2/a^2 + y^2/b^2 = 1 (a > b). Semi-axes a and b; foci on the long axis at distance c where c^2 = a^2 - b^2; eccentricity e = c/a < 1.\nHYPERBOLA: x^2/a^2 - y^2/b^2 = 1. Here c^2 = a^2 + b^2, e = c/a > 1, and the asymptotes are the lines y = ± (b/a) x.\nPARABOLA: y^2 = 2 p x opens sideways; focus at (p/2, 0), directrix x = -p/2. Every point is equidistant from focus and directrix.\nRead the equation first: a PLUS between the squared terms => ellipse (or circle if a = b); a MINUS => hyperbola; only ONE squared term => parabola. That single check picks the right formula set.", "ОКРУЖНОСТЬ: (x - a)^2 + (y - b)^2 = r^2, центр (a, b), радиус r.\nЭЛЛИПС: x^2/a^2 + y^2/b^2 = 1 (a > b). Полуоси a и b; фокусы на большой оси на расстоянии c, где c^2 = a^2 - b^2; эксцентриситет e = c/a < 1.\nГИПЕРБОЛА: x^2/a^2 - y^2/b^2 = 1. Здесь c^2 = a^2 + b^2, e = c/a > 1, асимптоты — прямые y = ± (b/a) x.\nПАРАБОЛА: y^2 = 2 p x открыта вбок; фокус в (p/2, 0), директриса x = -p/2. Любая точка равноудалена от фокуса и директрисы.\nСначала читаешь уравнение: ПЛЮС между квадратами => эллипс (или окружность при a = b); МИНУС => гипербола; только ОДИН квадрат => парабола. Эта проверка сразу выбирает нужный набор формул.", "csca.app: 15 задач на кривые второго порядка. Для каждой определи тип по знаку, потом найди c, e и асимптоты.", 50],
  ["Векторы и скалярное произведение", "A vector a = (a_1, a_2) has length |a| = sqrt(a_1^2 + a_2^2). Add / subtract componentwise; scale by multiplying each component.\nDOT PRODUCT: a · b = a_1 b_1 + a_2 b_2 = |a| |b| cos θ, where θ is the angle between them. So the angle is cos θ = (a · b) / (|a| |b|).\nKey facts: a · b = 0  <=>  the vectors are PERPENDICULAR; if a · b > 0 the angle is acute, if < 0 obtuse. Two vectors are PARALLEL when one is a scalar multiple of the other, i.e. a_1 b_2 - a_2 b_1 = 0.\nCSCA loves: 'find k so that (…) is perpendicular to (…)' — set the dot product to 0 and solve.", "Вектор a = (a_1, a_2) имеет длину |a| = sqrt(a_1^2 + a_2^2). Складывают и вычитают покоординатно; умножают на число — каждую координату.\nСКАЛЯРНОЕ ПРОИЗВЕДЕНИЕ: a · b = a_1 b_1 + a_2 b_2 = |a| |b| cos θ, где θ — угол между ними. Отсюда cos θ = (a · b) / (|a| |b|).\nГлавное: a · b = 0  <=>  векторы ПЕРПЕНДИКУЛЯРНЫ; при a · b > 0 угол острый, при < 0 тупой. Векторы КОЛЛИНЕАРНЫ (параллельны), когда один — кратное другого, то есть a_1 b_2 - a_2 b_1 = 0.\nCSCA обожает: «найди k, при котором (…) перпендикулярно (…)» — приравняй скалярное произведение к 0 и реши.", "csca.app: 12 задач на длину, угол и перпендикулярность векторов.", 40],
  ["Комплексные числа", "A complex number z = a + b i, where i^2 = -1; a is the real part, b the imaginary part. Arithmetic is like binomials, replacing i^2 by -1:\n  (a + bi)(c + di) = (ac - bd) + (ad + bc) i.\nMODULUS: |z| = sqrt(a^2 + b^2) (distance from the origin). CONJUGATE: z-bar = a - b i. Handy: z * z-bar = a^2 + b^2 = |z|^2.\nTo DIVIDE, multiply top and bottom by the conjugate of the denominator to make it real:\n  (a + bi)/(c + di) = (a + bi)(c - di) / (c^2 + d^2).\nPowers of i cycle with period 4: i, -1, -i, 1, i, … so i^n depends only on n mod 4.", "Комплексное число z = a + b i, где i^2 = -1; a — действительная часть, b — мнимая. Арифметика как с двучленами, только i^2 заменяем на -1:\n  (a + bi)(c + di) = (ac - bd) + (ad + bc) i.\nМОДУЛЬ: |z| = sqrt(a^2 + b^2) (расстояние от начала координат). СОПРЯЖЁННОЕ: z-с чертой = a - b i. Полезно: z * z-сопр = a^2 + b^2 = |z|^2.\nЧтобы ПОДЕЛИТЬ, умножь числитель и знаменатель на сопряжённое знаменателя — знаменатель станет действительным:\n  (a + bi)/(c + di) = (a + bi)(c - di) / (c^2 + d^2).\nСтепени i цикличны с периодом 4: i, -1, -i, 1, i, … поэтому i^n зависит только от n mod 4.", "csca.app: 12 задач на модуль, сопряжённое и деление комплексных чисел.", 40],
  ["Введение в анализ: пределы и производная", "A LIMIT lim(x->a) f(x) is the value f(x) approaches near a. For a polynomial or a continuous function you just substitute. If you get 0/0, FACTOR and cancel, e.g. (x^2 - 4)/(x - 2) = x + 2 -> 4 as x -> 2.\nThe DERIVATIVE f'(x) is the instantaneous rate of change / the slope of the tangent. Power rule: (x^n)' = n x^(n-1). Also (c)' = 0, (sin x)' = cos x, (cos x)' = -sin x, (e^x)' = e^x, (ln x)' = 1/x.\nRules: (f g)' = f' g + f g' (product), (f/g)' = (f' g - f g')/g^2 (quotient), chain rule (f(g(x)))' = f'(g) * g'.\nUse it to find tangents (slope = f'(x_0)) and extrema (f'(x) = 0, then check the sign change).", "ПРЕДЕЛ lim(x->a) f(x) — значение, к которому стремится f(x) около a. Для многочлена или непрерывной функции просто подставляешь. Если вышло 0/0, РАЗЛОЖИ на множители и сократи: (x^2 - 4)/(x - 2) = x + 2 -> 4 при x -> 2.\nПРОИЗВОДНАЯ f'(x) — мгновенная скорость изменения / наклон касательной. Степенное правило: (x^n)' = n x^(n-1). Ещё (c)' = 0, (sin x)' = cos x, (cos x)' = -sin x, (e^x)' = e^x, (ln x)' = 1/x.\nПравила: (f g)' = f' g + f g' (произведение), (f/g)' = (f' g - f g')/g^2 (частное), цепное (f(g(x)))' = f'(g) * g'.\nПрименение: касательная (наклон = f'(x_0)) и экстремумы (f'(x) = 0, затем смотришь смену знака).", "csca.app: 12-15 задач на пределы (0/0) и производную (правила + касательная). Экстремумы — по смене знака f'.", 50],
  ["Вероятность и статистика", "Basic probability: P(A) = (favourable outcomes) / (all equally likely outcomes), always between 0 and 1. Complement: P(not A) = 1 - P(A).\nUnion: P(A or B) = P(A) + P(B) - P(A and B). If A and B are MUTUALLY EXCLUSIVE, the last term is 0. If they are INDEPENDENT, P(A and B) = P(A) * P(B).\nCOUNTING: permutations (order matters) nPr = n! / (n - r)!; combinations (order does not) nCr = n! / (r! (n - r)!).\nSTATISTICS: mean = sum / count; the median is the middle value when sorted; variance is the average of squared deviations from the mean, and standard deviation is its square root. These are cheap, reliable points on the test — don't skip them.", "Базовая вероятность: P(A) = (благоприятные исходы) / (все равновозможные исходы), всегда от 0 до 1. Дополнение: P(не A) = 1 - P(A).\nОбъединение: P(A или B) = P(A) + P(B) - P(A и B). Если A и B НЕСОВМЕСТНЫ, последнее слагаемое = 0. Если НЕЗАВИСИМЫ, P(A и B) = P(A) * P(B).\nКОМБИНАТОРИКА: размещения (порядок важен) nPr = n! / (n - r)!; сочетания (порядок не важен) nCr = n! / (r! (n - r)!).\nСТАТИСТИКА: среднее = сумма / количество; медиана — серединное значение в отсортированном ряду; дисперсия — среднее квадратов отклонений от среднего, стандартное отклонение — корень из неё. Это дешёвые и надёжные баллы — не пропускай.", "csca.app: 12 задач на вероятность, комбинаторику и среднее/дисперсию.", 40],
];

export const CSCA_MOCK = ["Timed mock: полный экзамен", "Full timed mock exam: about 48 questions in 60 minutes, strict timer (roughly 1 min 15 sec per question). Do it in one sitting, then review EVERY mistake and redo it from scratch without hints.", "Полный mock по таймеру: примерно 48 вопросов за 60 минут, строгий таймер (около 1 мин 15 сек на вопрос). Реши за один присест, потом разбери КАЖДУЮ ошибку и перерешай её с нуля без подсказок.", "csca.app: запусти полный timed mock. После — разбор всех ошибок в mistake log.", 75];

export const CSCA_RESOURCES = [
  ["csca.app", "https://csca.app", "758 задач, интерактивные пробники, бесплатно"],
  ["crosslineedu.com", "https://crosslineedu.com", "разборы программы, free mock exams"],
  ["cucas.cn/csca", "https://www.cucas.cn/csca", "документы, программа, отзывы"],
];

export const DET_PROGRAM = [
  ["Read and Complete (fill the blanks)", "Дают абзац, где у части слов стёрты хвосты. Восстанавливаешь по контексту и грамматике. Тренируй скорость: читай всё предложение целиком, а не буквы. Практика — 2-3 текста.", "Tip: guess the word from context first, then fill missing letters.", 15],
  ["Read and Select (real vs fake words)", "Список слов — отметь, какие настоящие английские, а какие выдуманные. Растёт на объёме словаря. Веди список новых слов из ошибок и повторяй.", "Tip: if you have never seen it and it 'feels' odd, it is usually fake.", 15],
  ["Listen and Type (dictation)", "Слушаешь фразу (можно 3 раза) и печатаешь её точь-в-точь. Тренируй аудирование: артикли, окончания -s/-ed, слабые формы (of, to, and). 5-8 диктовок.", "Tip: type what you hear immediately, fix spelling on the last replay.", 20],
  ["Read Aloud (speaking)", "Читаешь предложение вслух — оценивают произношение и беглость. Запиши себя на телефон, сравни с оригиналом, следи за ударением в словах.", "Tip: slow and clear beats fast and mumbled. Mind word stress.", 15],
  ["Write about the Photo", "Описываешь картинку 1+ предложением за 1 минуту. Шаблон: что видишь + где + что происходит. Пиши полными предложениями, без ошибок в артиклях.", "Tip: 'There is/are …', present continuous for actions ('A man is …').", 15],
  ["Speak about the Photo / topic", "Говоришь про картинку или тему 30-90 секунд. Держи структуру: вступление, 2-3 детали, вывод. Не молчи — беглость важнее идеальной грамматики.", "Tip: keep talking; use fillers naturally ('what I notice is…').", 15],
  ["Interactive Reading", "Большой блок: заполнить пропуски, выбрать заголовок, ответить на вопросы по тексту. Читай первый и последний абзац внимательно — там суть.", "Tip: read the questions first, then scan the passage for answers.", 20],
  ["Interactive Listening / Summarize", "Слушаешь разговор, отвечаешь по ходу и в конце пишешь краткое summary. Держи в голове кто/что/зачем. Summary — 2-3 своих предложения, не копипаст.", "Tip: note the speaker's goal; your summary should answer 'what did they decide?'.", 20],
  ["Writing Sample (long answer)", "5 минут на развёрнутый ответ по теме. Структура на 3 абзаца: тезис — 2 причины с примерами — вывод. Цель: 120-160 слов без грубых ошибок.", "Tip: linkers — 'Firstly', 'For example', 'In conclusion'. Reread once.", 20],
  ["Speaking Sample (long answer)", "1-3 минуты монолога на тему. Тот же каркас, что в письме: мнение — аргументы — вывод. Запиши и переслушай: паузы, повторы, произношение.", "Tip: it is fine to pause to think; avoid long silent gaps.", 20],
  ["Full adaptive practice test", "Пройди официальный бесплатный practice test целиком по таймеру — понять текущий балл и слабые секции. Потом добивай именно слабое.", "Tip: treat it like the real thing — quiet room, no pauses, one go.", 40],
];

export const DET_RESOURCES = [
  ["Официальный практик-тест", "https://englishtest.duolingo.com/prep", "бесплатный пробный DET, показывает балл"],
  ["englishtest.duolingo.com", "https://englishtest.duolingo.com", "регистрация, правила, окно экзамена"],
  ["Duolingo English Test — accepted institutions", "https://englishtest.duolingo.com/institutions", "проверь минимальный балл нужных вузов Китая"],
];

export const EGE_VARIANTS = [
  ["Профильный вариант (случайный)", "https://ege.sdamgia.ru/test?a=catgen"],
  ["Досрочный вариант ФИПИ", "https://mathb-ege.sdamgia.ru/"],
  ["Вариант из открытого банка ФИПИ", "https://fipi.ru/ege/otkrytyy-bank-zadaniy-ege"],
];

export function sixMinTask(index) {
  const ep = SIX_MIN_EPISODES[index % SIX_MIN_EPISODES.length];
  return { number: 142 + index, title: ep[0], link: ep[1], minutes: 10 };
}

export function cscaTask(index) {
  let title, english, russian, task, minutes, block;
  if (index < CSCA_LESSONS.length) {
    [title, english, russian, task, minutes] = CSCA_LESSONS[index];
    block = index + 1;
  } else {
    [title, english, russian, task, minutes] = CSCA_MOCK;
    block = CSCA_LESSONS.length + (index - CSCA_LESSONS.length + 1);
  }
  return { block, title, english, russian, link: CSCA_APP, task, minutes };
}

export function detTask(index) {
  const [title, desc, tip, minutes] = DET_PROGRAM[index % DET_PROGRAM.length];
  return { number: index + 1, title, desc, tip, link: DET_PRACTICE, minutes };
}

export function egeTask(index) {
  const v = EGE_VARIANTS[index % EGE_VARIANTS.length];
  return { title: v[0], link: v[1], minutes: 120 };
}
